import { z } from 'zod';

/**
 * Game Question - Generated by AI for the emoji guessing game
 */
export const GameQuestionSchema = z.object({
  emoji: z.string(),
  correctAnswer: z.string(),
  wrongAnswers: z.array(z.string()).length(2),
});
export type GameQuestion = z.infer<typeof GameQuestionSchema>;

/**
 * Game Attempt - A single user attempt at answering a question
 */
export const GameAttemptSchema = z.object({
  id: z.string().uuid(),
  sessionId: z.string().uuid(),
  questionEmoji: z.string(),
  correctAnswer: z.string(),
  userAnswer: z.string(),
  isCorrect: z.boolean(),
  attemptNumber: z.number().int().min(1).max(2),
  timestamp: z.number(),
});
export type GameAttempt = z.infer<typeof GameAttemptSchema>;

/**
 * Game Session - A single game session (can contain multiple questions)
 */
export const GameSessionSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  score: z.number().int().min(0),
  correctAnswers: z.number().int().min(0),
  wrongAnswers: z.number().int().min(0),
  totalQuestions: z.number().int().min(0),
  currentStreak: z.number().int().min(0),
  startedAt: z.number(),
  endedAt: z.number().nullable(),
});
export type GameSession = z.infer<typeof GameSessionSchema>;

/**
 * Game Stats - Aggregated statistics across all sessions
 */
export const GameStatsSchema = z.object({
  totalQuestions: z.number().int().min(0),
  correctAnswers: z.number().int().min(0),
  wrongAnswers: z.number().int().min(0),
  accuracy: z.number().min(0).max(1),
  currentStreak: z.number().int().min(0),
  bestStreak: z.number().int().min(0),
  totalSessions: z.number().int().min(0),
  averageScore: z.number().min(0),
});
export type GameStats = z.infer<typeof GameStatsSchema>;

/**
 * Default game stats for new users
 */
export const DEFAULT_GAME_STATS: GameStats = {
  totalQuestions: 0,
  correctAnswers: 0,
  wrongAnswers: 0,
  accuracy: 0,
  currentStreak: 0,
  bestStreak: 0,
  totalSessions: 0,
  averageScore: 0,
};

